name: Code Scan (SonarQube)

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for PR decorations)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: SonarQube Scan (Gradle)
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: 00755702faec89df41e4d552604769e03be5d1d8
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=rare-beauty_makeup-website
            -Dsonar.organization=rare-beauty
            -Dsonar.sources=.
            -Dsonar.exclusions="**/node_modules/**,**/dist/**,**/build/**"

      - name: Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: 00755702faec89df41e4d552604769e03be5d1d8
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt
